[Paths]
pathwork = /home/kali/Documents/AutoRpt

[Settings]
exam = training
your_name = A. B.
email = a@b.c
studentid = OS-12345
preferred_output_format = odt
style = haddock
output_formats = pdf, pdf+7z, docx, odt, jira, commonmark_x, gfm
no_template = docx

[Files]
sessionfile = sessions.yml
targetfile = targets.txt
portfile = ports.xlsx
vulnfile = vulns.csv
sitrepfile = sitrep.log

