[Paths]
pathwork = /home/kali/Documents/AutoRpt

[Settings]
types = training,ctf,exam,bugbounty,pentest
your_name = 
email = 
studentid = 
preferred_output_format = odt
style = haddock
output_formats = pdf,pdf+7z,docx,odt,jira,commonmark_x,gfm
no_template = docx

[Files]
sessionfile = sessions.yml
targetfile = targets.txt
portfile = ports.xlsx
vulnfile = vulns.csv
sitrepfile = sitrep.log

[Training]
Hack the Box = hackthebox
Try Hack Me = tryhackme
VulnHub = vulnhub
Proving Grounds = provinggrounds
Virtual Hacking Labs = virtualhackinglabs
SANS NetWars = sansnetwars
PortSwigger Web Security Academy = websecurityacademy

[Bug Bounty]
Bug Crowd = bugcrowd
Hacker One = hackerone
SynAck = synack

[Exams]
oscp = offensivesecurity,Offensive Security Certified Professional
osep = offensivesecurity,Offensive Security Experienced Penetration Tester
osed = offensivesecurity,Offensive Security Exploit Developer
oswe = offensivesecurity,Offensive Security Web Expert
osee = offensivesecurity,Offensive Security Exploitation Expert
pnpt = tcmsecurity,Practical Network Penetration Tester
ejpt = elearnsecurity,Junior Penetration Tester
ecppt = elearnsecurity,Certified Penetration Tester
ewpt = elearnsecurity,Web Application Penetration Tester
ewptx = elearnsecurity,Web Application Penetration Tester eXtreme
bscp = portswigger,Burp Suite Certified Practitioner